version: 0.2

env:
  variables:
    LAMBDA_FUNCTION: "lambda_function"  # This will be overridden by CodeBuild

phases:
  install:
    runtime-versions:
      java: corretto21
  
  build:
    commands:
      - echo Building Lambda function: $LAMBDA_FUNCTION
      - echo Build started on `date`
      - ./gradlew build -PfunctionName=$LAMBDA_FUNCTION
      
  post_build:
    commands:
      - echo Build completed on `date`
      - pip install boto3 pyyaml python-hcl2
      - python3 codeBuild/generate_appspec.py

artifacts:
  files:
    - appspec.yml
    - build/distributions/FryRankLambda.zip
  discard-paths: yes