version: 0.2

env:
  variables:
    LAMBDA_ZIP_KEY: "FryRankLambda.zip"

phases:
  install:
    runtime-versions:
      java: corretto21
      python: 3.11
    commands:
      - pip install boto3

  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Starting Lambda function updates..."
      - python codeBuild/update_lambdas.py

artifacts:
  files:
    - build/distributions/FryRankLambda.zip
  discard-paths: yes
