version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - pip install -r codeBuild/test/requirements.txt
  
  test:
    commands:
      - echo Running tests...
      - python3 codeBuild/test/test_generate_appspec.py
  
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      
  post_build:
    commands:
      - echo Build completed on `date`
      - python3 codeBuild/generate_appspec.py
      - echo Generated AppSpec files:
      - ls -la appspec-*.yml

artifacts:
  files:
    - appspec-*.yml
    - build/distributions/FryRankLambda.zip
  discard-paths: yes
