version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      
  post_build:
    commands:
      - echo Build completed on `date`
      - pip install boto3 pyyaml python-hcl2
      - python3 codeBuild/generate_appspec.py
      - echo Generated AppSpec files:
      - ls -la appspec-*.yml

artifacts:
  files:
    - appspec-*.yml
    - build/distributions/FryRankLambda.zip
  discard-paths: yes
