version: 0.2

env:
  variables:
    S3_BUCKET: "fryrank-terraform-state-bucket"
    S3_KEY: "FryRankLambda.zip"
    TERRAFORM_STATE_BUCKET: "fryrank-terraform-state-bucket"

phases:
  install:
    runtime-versions:
      java: corretto21
      python: 3.11
    commands:
      - pip install boto3
  
  build:
    commands:
      - echo Building Lambda function: $LAMBDA_FUNCTION
      - echo Build started on `date`
      - ./gradlew build -PfunctionName=$LAMBDA_FUNCTION
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Starting Lambda function updates..."
      - python codeBuild/update_lambdas.py

artifacts:
  files:
    - build/distributions/FryRankLambda.zip
  discard-paths: yes